server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: password
    
      
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

spring.sql.init.mode: never


logging:
  level:
    root: INFO
